apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: prometheus-tunnel
  name: prometheus-tunnel
spec:
  podMetricsEndpoints:
    - interval: 15s
      port: metrics
  selector:
    matchLabels:
      app: prometheus-tunnel
