apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-tunnel
  labels:
    prometheus: prometheus-tunnel
spec:
  groups:
  - name: prometheus-tunnel.rules
    rules:
    - alert: HighRequestRate
      expr: rate(proxy_total_requests[5m]) > 100
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High Request Rate"
        description: "The request rate has exceeded 100 requests per minute."

    - alert: SlowRequestDuration
      expr: histogram_quantile(0.99, rate(proxy_request_duration_seconds_bucket[5m])) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Slow Request Duration"
        description: "99th percentile request duration is greater than 1 second."

    - alert: HighErrorRate
      expr: rate(proxy_response_status_total{status=~"5.."}[5m]) > 10
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High Error Rate"
        description: "The rate of 5xx errors has exceeded 10 errors per minute."

    - alert: HighLatency
      expr: rate(proxy_request_duration_seconds_sum[5m]) / rate(proxy_request_duration_seconds_count[5m]) > 0.5
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High Request Latency"
        description: "The average request latency is greater than 0.5 seconds."

    - alert: HighRequestVolume
      expr: sum(rate(proxy_total_requests[5m])) by (job) > 1000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High Request Volume"
        description: "The total request volume has exceeded 1000 requests per minute."
