apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: prometheus-tunnel
    release: "{{ .Release.Name }}"
    prometheus-tunnel/serverIP: "{{ .Values.settings.serverIP }}"
    prometheus-tunnel/serverPort: "{{ .Values.settings.serverPort }}"
    prometheus-tunnel/name: "{{ .Values.settings.name }}"
automountServiceAccountToken: true
