apiVersion: v1
kind: Service
metadata:
  name: "pvc-monitor"
  labels:
    app: "pvc-monitor"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.service.port }}
      targetPort: {{.Values.service.port }}
      protocol: TCP
      name: metrics
  selector:
    app: "pvc-monitor"
