apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-tunnel
    release: "{{ .Release.Name }}"
    prometheus-tunnel/serverIP: "{{ .Values.settings.serverIP }}"
    prometheus-tunnel/serverPort: "{{ .Values.settings.serverPort }}"
    prometheus-tunnel/name: "{{ .Values.settings.name }}"    
  name: "{{ .Release.Name }}"
spec:
  endpoints:
    - interval: 15s
      port: metrics
  selector:
    matchLabels:
      app: prometheus-tunnel
      release: "{{ .Release.Name }}"
      prometheus-tunnel/serverIP: "{{ .Values.settings.serverIP }}"
      prometheus-tunnel/serverPort: "{{ .Values.settings.serverPort }}"
      prometheus-tunnel/name: "{{ .Values.settings.name }}"      
