apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: pvc-monitor
  name: pvc-monitor
spec:
  endpoints:
    - interval: 15s
      port: metrics
  selector:
    matchLabels:
      app: pvc-monitor
