apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-tunnel
  name: prometheus-tunnel
spec:
  endpoints:
    - interval: 15s
      port: metrics
  selector:
    matchLabels:
      app: prometheus-tunnel
