apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "prometheus-tunnel"
    release: "{{ .Release.Name }}"
    prometheus-tunnel/serverIP: "{{ .Values.settings.serverIP }}"
    prometheus-tunnel/serverPort: "{{ .Values.settings.serverPort }}"
    prometheus-tunnel/name: "{{ .Values.settings.name }}"    
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port | int }}"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.settings.serverPort | int }}
      targetPort: {{ .Values.settings.serverPort | int }}
      protocol: TCP
    - name: internalmetrics
      port: {{ .Values.settings.metrics.port | int }}
      targetPort: {{ .Values.settings.metrics.port | int }}
      protocol: TCP
  clusterIP: None
  selector:
    app: "prometheus-tunnel"
    prometheus-tunnel/serverIP: "{{ .Values.settings.serverIP }}"
    prometheus-tunnel/serverPort: "{{ .Values.settings.serverPort }}"
    prometheus-tunnel/name: "{{ .Values.settings.name }}"
